spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:voting
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      continue-on-error: true

