CREATE TABLE if not exists CUSTOMERS
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    surname      VARCHAR(255) NOT NULL,
    age          int          NOT NULL,
    phone_number VARCHAR(50)  NOT NULL
);

CREATE TABLE if not exists ORDERS
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date         TIMESTAMP DEFAULT now() not null,
    customer_id  INTEGER                 NOT NULL,
    product_name VARCHAR(255)            NOT NULL,
    amount       FLOAT                   NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES CUSTOMERS (id) ON DELETE CASCADE
);

